/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as RegisterSplatRouteImport } from './routes/register.$'
import { Route as LoginSplatRouteImport } from './routes/login.$'
import { Route as AlbumsSlugRouteImport } from './routes/albums.$slug'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminPhotosIndexRouteImport } from './routes/admin.photos.index'
import { Route as AdminAlbumsIndexRouteImport } from './routes/admin.albums.index'
import { Route as AdminPhotosUploadRouteImport } from './routes/admin.photos.upload'
import { Route as AdminPhotosPhotoIdRouteImport } from './routes/admin.photos.$photoId'
import { Route as AdminAlbumsNewRouteImport } from './routes/admin.albums.new'
import { Route as AdminAlbumsSlugRouteImport } from './routes/admin.albums.$slug'
import { Route as AdminPhotosPhotoIdEditRouteImport } from './routes/admin.photos.$photoId.edit'
import { Route as ApiIUserIdPhotoIdFileRouteImport } from './routes/api/i.$userId.$photoId.$file'
import { Route as AdminAlbumsSlugPhotosPhotoIdRouteImport } from './routes/admin.albums_.$slug.photos.$photoId'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const RegisterSplatRoute = RegisterSplatRouteImport.update({
  id: '/register/$',
  path: '/register/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginSplatRoute = LoginSplatRouteImport.update({
  id: '/login/$',
  path: '/login/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsSlugRoute = AlbumsSlugRouteImport.update({
  id: '/albums/$slug',
  path: '/albums/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPhotosIndexRoute = AdminPhotosIndexRouteImport.update({
  id: '/photos/',
  path: '/photos/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlbumsIndexRoute = AdminAlbumsIndexRouteImport.update({
  id: '/albums/',
  path: '/albums/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPhotosUploadRoute = AdminPhotosUploadRouteImport.update({
  id: '/photos/upload',
  path: '/photos/upload',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPhotosPhotoIdRoute = AdminPhotosPhotoIdRouteImport.update({
  id: '/photos/$photoId',
  path: '/photos/$photoId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlbumsNewRoute = AdminAlbumsNewRouteImport.update({
  id: '/albums/new',
  path: '/albums/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlbumsSlugRoute = AdminAlbumsSlugRouteImport.update({
  id: '/albums/$slug',
  path: '/albums/$slug',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPhotosPhotoIdEditRoute = AdminPhotosPhotoIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AdminPhotosPhotoIdRoute,
} as any)
const ApiIUserIdPhotoIdFileRoute = ApiIUserIdPhotoIdFileRouteImport.update({
  id: '/api/i/$userId/$photoId/$file',
  path: '/api/i/$userId/$photoId/$file',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAlbumsSlugPhotosPhotoIdRoute =
  AdminAlbumsSlugPhotosPhotoIdRouteImport.update({
    id: '/albums_/$slug/photos/$photoId',
    path: '/albums/$slug/photos/$photoId',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/albums/$slug': typeof AlbumsSlugRoute
  '/login/$': typeof LoginSplatRoute
  '/register/$': typeof RegisterSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/albums/$slug': typeof AdminAlbumsSlugRoute
  '/admin/albums/new': typeof AdminAlbumsNewRoute
  '/admin/photos/$photoId': typeof AdminPhotosPhotoIdRouteWithChildren
  '/admin/photos/upload': typeof AdminPhotosUploadRoute
  '/admin/albums/': typeof AdminAlbumsIndexRoute
  '/admin/photos/': typeof AdminPhotosIndexRoute
  '/admin/photos/$photoId/edit': typeof AdminPhotosPhotoIdEditRoute
  '/admin/albums/$slug/photos/$photoId': typeof AdminAlbumsSlugPhotosPhotoIdRoute
  '/api/i/$userId/$photoId/$file': typeof ApiIUserIdPhotoIdFileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/albums/$slug': typeof AlbumsSlugRoute
  '/login/$': typeof LoginSplatRoute
  '/register/$': typeof RegisterSplatRoute
  '/admin': typeof AdminIndexRoute
  '/admin/albums/$slug': typeof AdminAlbumsSlugRoute
  '/admin/albums/new': typeof AdminAlbumsNewRoute
  '/admin/photos/$photoId': typeof AdminPhotosPhotoIdRouteWithChildren
  '/admin/photos/upload': typeof AdminPhotosUploadRoute
  '/admin/albums': typeof AdminAlbumsIndexRoute
  '/admin/photos': typeof AdminPhotosIndexRoute
  '/admin/photos/$photoId/edit': typeof AdminPhotosPhotoIdEditRoute
  '/admin/albums/$slug/photos/$photoId': typeof AdminAlbumsSlugPhotosPhotoIdRoute
  '/api/i/$userId/$photoId/$file': typeof ApiIUserIdPhotoIdFileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/albums/$slug': typeof AlbumsSlugRoute
  '/login/$': typeof LoginSplatRoute
  '/register/$': typeof RegisterSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/albums/$slug': typeof AdminAlbumsSlugRoute
  '/admin/albums/new': typeof AdminAlbumsNewRoute
  '/admin/photos/$photoId': typeof AdminPhotosPhotoIdRouteWithChildren
  '/admin/photos/upload': typeof AdminPhotosUploadRoute
  '/admin/albums/': typeof AdminAlbumsIndexRoute
  '/admin/photos/': typeof AdminPhotosIndexRoute
  '/admin/photos/$photoId/edit': typeof AdminPhotosPhotoIdEditRoute
  '/admin/albums_/$slug/photos/$photoId': typeof AdminAlbumsSlugPhotosPhotoIdRoute
  '/api/i/$userId/$photoId/$file': typeof ApiIUserIdPhotoIdFileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/settings'
    | '/albums/$slug'
    | '/login/$'
    | '/register/$'
    | '/admin/'
    | '/admin/albums/$slug'
    | '/admin/albums/new'
    | '/admin/photos/$photoId'
    | '/admin/photos/upload'
    | '/admin/albums/'
    | '/admin/photos/'
    | '/admin/photos/$photoId/edit'
    | '/admin/albums/$slug/photos/$photoId'
    | '/api/i/$userId/$photoId/$file'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/settings'
    | '/albums/$slug'
    | '/login/$'
    | '/register/$'
    | '/admin'
    | '/admin/albums/$slug'
    | '/admin/albums/new'
    | '/admin/photos/$photoId'
    | '/admin/photos/upload'
    | '/admin/albums'
    | '/admin/photos'
    | '/admin/photos/$photoId/edit'
    | '/admin/albums/$slug/photos/$photoId'
    | '/api/i/$userId/$photoId/$file'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/settings'
    | '/albums/$slug'
    | '/login/$'
    | '/register/$'
    | '/admin/'
    | '/admin/albums/$slug'
    | '/admin/albums/new'
    | '/admin/photos/$photoId'
    | '/admin/photos/upload'
    | '/admin/albums/'
    | '/admin/photos/'
    | '/admin/photos/$photoId/edit'
    | '/admin/albums_/$slug/photos/$photoId'
    | '/api/i/$userId/$photoId/$file'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AlbumsSlugRoute: typeof AlbumsSlugRoute
  LoginSplatRoute: typeof LoginSplatRoute
  RegisterSplatRoute: typeof RegisterSplatRoute
  ApiIUserIdPhotoIdFileRoute: typeof ApiIUserIdPhotoIdFileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/register/$': {
      id: '/register/$'
      path: '/register/$'
      fullPath: '/register/$'
      preLoaderRoute: typeof RegisterSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/$': {
      id: '/login/$'
      path: '/login/$'
      fullPath: '/login/$'
      preLoaderRoute: typeof LoginSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums/$slug': {
      id: '/albums/$slug'
      path: '/albums/$slug'
      fullPath: '/albums/$slug'
      preLoaderRoute: typeof AlbumsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/photos/': {
      id: '/admin/photos/'
      path: '/photos'
      fullPath: '/admin/photos/'
      preLoaderRoute: typeof AdminPhotosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/albums/': {
      id: '/admin/albums/'
      path: '/albums'
      fullPath: '/admin/albums/'
      preLoaderRoute: typeof AdminAlbumsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/photos/upload': {
      id: '/admin/photos/upload'
      path: '/photos/upload'
      fullPath: '/admin/photos/upload'
      preLoaderRoute: typeof AdminPhotosUploadRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/photos/$photoId': {
      id: '/admin/photos/$photoId'
      path: '/photos/$photoId'
      fullPath: '/admin/photos/$photoId'
      preLoaderRoute: typeof AdminPhotosPhotoIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/albums/new': {
      id: '/admin/albums/new'
      path: '/albums/new'
      fullPath: '/admin/albums/new'
      preLoaderRoute: typeof AdminAlbumsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/albums/$slug': {
      id: '/admin/albums/$slug'
      path: '/albums/$slug'
      fullPath: '/admin/albums/$slug'
      preLoaderRoute: typeof AdminAlbumsSlugRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/photos/$photoId/edit': {
      id: '/admin/photos/$photoId/edit'
      path: '/edit'
      fullPath: '/admin/photos/$photoId/edit'
      preLoaderRoute: typeof AdminPhotosPhotoIdEditRouteImport
      parentRoute: typeof AdminPhotosPhotoIdRoute
    }
    '/api/i/$userId/$photoId/$file': {
      id: '/api/i/$userId/$photoId/$file'
      path: '/api/i/$userId/$photoId/$file'
      fullPath: '/api/i/$userId/$photoId/$file'
      preLoaderRoute: typeof ApiIUserIdPhotoIdFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/albums_/$slug/photos/$photoId': {
      id: '/admin/albums_/$slug/photos/$photoId'
      path: '/albums/$slug/photos/$photoId'
      fullPath: '/admin/albums/$slug/photos/$photoId'
      preLoaderRoute: typeof AdminAlbumsSlugPhotosPhotoIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminPhotosPhotoIdRouteChildren {
  AdminPhotosPhotoIdEditRoute: typeof AdminPhotosPhotoIdEditRoute
}

const AdminPhotosPhotoIdRouteChildren: AdminPhotosPhotoIdRouteChildren = {
  AdminPhotosPhotoIdEditRoute: AdminPhotosPhotoIdEditRoute,
}

const AdminPhotosPhotoIdRouteWithChildren =
  AdminPhotosPhotoIdRoute._addFileChildren(AdminPhotosPhotoIdRouteChildren)

interface AdminRouteChildren {
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAlbumsSlugRoute: typeof AdminAlbumsSlugRoute
  AdminAlbumsNewRoute: typeof AdminAlbumsNewRoute
  AdminPhotosPhotoIdRoute: typeof AdminPhotosPhotoIdRouteWithChildren
  AdminPhotosUploadRoute: typeof AdminPhotosUploadRoute
  AdminAlbumsIndexRoute: typeof AdminAlbumsIndexRoute
  AdminPhotosIndexRoute: typeof AdminPhotosIndexRoute
  AdminAlbumsSlugPhotosPhotoIdRoute: typeof AdminAlbumsSlugPhotosPhotoIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAlbumsSlugRoute: AdminAlbumsSlugRoute,
  AdminAlbumsNewRoute: AdminAlbumsNewRoute,
  AdminPhotosPhotoIdRoute: AdminPhotosPhotoIdRouteWithChildren,
  AdminPhotosUploadRoute: AdminPhotosUploadRoute,
  AdminAlbumsIndexRoute: AdminAlbumsIndexRoute,
  AdminPhotosIndexRoute: AdminPhotosIndexRoute,
  AdminAlbumsSlugPhotosPhotoIdRoute: AdminAlbumsSlugPhotosPhotoIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AlbumsSlugRoute: AlbumsSlugRoute,
  LoginSplatRoute: LoginSplatRoute,
  RegisterSplatRoute: RegisterSplatRoute,
  ApiIUserIdPhotoIdFileRoute: ApiIUserIdPhotoIdFileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
